// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwpj7do9ZoQ-wQ9taMbWJHbogm0mQt-Cs',
    appId: '1:888501380095:web:038b0a964b974e881b7dca',
    messagingSenderId: '888501380095',
    projectId: 'wastenavigate',
    authDomain: 'wastenavigate.firebaseapp.com',
    storageBucket: 'wastenavigate.appspot.com',
    measurementId: 'G-ZXSCXHF8YV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUAejwR96_6RDv7Zo2JhBiz5qR4MvOZRE',
    appId: '1:888501380095:android:570c527934e4506e1b7dca',
    messagingSenderId: '888501380095',
    projectId: 'wastenavigate',
    storageBucket: 'wastenavigate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX8XYKotTd3TlkZCZ3mEJyqKMQtxNXbUE',
    appId: '1:888501380095:ios:623348873d23e9271b7dca',
    messagingSenderId: '888501380095',
    projectId: 'wastenavigate',
    storageBucket: 'wastenavigate.appspot.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX8XYKotTd3TlkZCZ3mEJyqKMQtxNXbUE',
    appId: '1:888501380095:ios:803dd872cb92c8031b7dca',
    messagingSenderId: '888501380095',
    projectId: 'wastenavigate',
    storageBucket: 'wastenavigate.appspot.com',
    iosBundleId: 'com.example.testApp.RunnerTests',
  );
}
