name: test_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
  # sdk: '>=2.2.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  line_awesome_flutter: ^2.0.0
  curved_navigation_bar: ^1.0.3 
  google_nav_bar: ^5.0.6
  get: ^4.6.6
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0
  shimmer: ^3.0.0
  flutter_svg: ^2.0.9
  firebase_core: ^2.25.5
  firebase_auth: ^4.17.6
  # google_sign_in: ^6.1.5
  # cloud_firestore: ^4.15.0
  carousel_slider: ^4.2.1
  google_maps_flutter: ^2.5.3
  google_sign_in: ^6.2.1
  location: ^5.0.3
  cloud_firestore: ^4.15.6
  flutter_spinkit: ^5.2.0
  # polyline: ^1.0.0
  geolocator: ^11.0.0
  geocoding: ^2.1.1
  rename: ^3.0.1
  rename_app: ^1.3.2
  camera: ^0.10.5+9
  flutter_otp_text_field: ^1.1.1
  permission_handler: ^11.3.0
  # google_fonts: ^6.2.1
  otp_text_field: ^1.1.3
  intl: ^0.19.0
  flutter_slidable: ^3.0.1

  scratcher: ^2.5.0
  web: ^0.4.2
  flutter_rating_bar: ^4.0.1
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.3
  path: ^1.9.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  flutter_google_places: ^0.3.0
  url_launcher: ^6.2.5
  # google_places_flutter: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.3.9
  flutter_lints: ^3.0.1
  flutter_launcher_icons: "^0.13.1"

flutter_native_splash:
  image: assets/images/logo_color.png
  color: "#ffffff"
  image_dark: assets/images/logo_white.png
  color_dark: "#000000"
  color_android: "#ffffff"
  color_dark_android: "#000000"
  
  android_12:
    image: assets/images/logo_color.png
    icon_background_color: "#ffffff"
    color: "#ffffff"
    image_dark: assets/images/logo_white.png
    icon_background_color_dark: "#000000"
    color_android: "#ffffff"
    color_dark_android: "#000000"

  # Define the scaling behavior
  android: true
  ios: true
  

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/splash_images/
    - assets/images/on_boarding_images/
    - assets/images/waste_post/
    - assets/images/scrollimg/
  



# flutter lauch icon changes

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_color.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon_color.png"
    background_color: "#65B741"
    theme_color: "#65B741"
  windows:
    generate: true
    image_path: "assets/images/icon_color.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icon_color.png"